// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import model "github.com/sirateek/terraform-provider-milvus/internal/resources/collection/model"

type ConverterImpl struct{}

func (c *ConverterImpl) MilvusCollectionPropertiesToParsed(source *model.MilvusCollectionProperties) *model.ParsedMilvusCollectionProperties {
	var pModelParsedMilvusCollectionProperties *model.ParsedMilvusCollectionProperties
	if source != nil {
		var modelParsedMilvusCollectionProperties model.ParsedMilvusCollectionProperties
		modelParsedMilvusCollectionProperties.TTLSeconds = TypesInt64ToInt64Ptr((*source).TTLSeconds)
		modelParsedMilvusCollectionProperties.MMapEnabled = TypesBoolToBoolPtr((*source).MMapEnabled)
		modelParsedMilvusCollectionProperties.PartitionKeyIsolation = TypesBoolToBoolPtr((*source).PartitionKeyIsolation)
		modelParsedMilvusCollectionProperties.DynamicFieldEnabled = TypesBoolToBoolPtr((*source).DynamicFieldEnabled)
		modelParsedMilvusCollectionProperties.AllowInsertAutoID = TypesBoolToBoolPtr((*source).AllowInsertAutoID)
		modelParsedMilvusCollectionProperties.AllowUpdateAutoID = TypesBoolToBoolPtr((*source).AllowUpdateAutoID)
		modelParsedMilvusCollectionProperties.Timezone = TypesStringToStringPtr((*source).Timezone)
		pModelParsedMilvusCollectionProperties = &modelParsedMilvusCollectionProperties
	}
	return pModelParsedMilvusCollectionProperties
}
func (c *ConverterImpl) ParsedToMilvusCollectionProperties(source *model.ParsedMilvusCollectionProperties) *model.MilvusCollectionProperties {
	var pModelMilvusCollectionProperties *model.MilvusCollectionProperties
	if source != nil {
		var modelMilvusCollectionProperties model.MilvusCollectionProperties
		modelMilvusCollectionProperties.TTLSeconds = Int64PtrToTypesInt64((*source).TTLSeconds)
		modelMilvusCollectionProperties.MMapEnabled = BoolPtrToTypesBool((*source).MMapEnabled)
		modelMilvusCollectionProperties.PartitionKeyIsolation = BoolPtrToTypesBool((*source).PartitionKeyIsolation)
		modelMilvusCollectionProperties.DynamicFieldEnabled = BoolPtrToTypesBool((*source).DynamicFieldEnabled)
		modelMilvusCollectionProperties.AllowInsertAutoID = BoolPtrToTypesBool((*source).AllowInsertAutoID)
		modelMilvusCollectionProperties.AllowUpdateAutoID = BoolPtrToTypesBool((*source).AllowUpdateAutoID)
		modelMilvusCollectionProperties.Timezone = StringPtrToTypesString((*source).Timezone)
		pModelMilvusCollectionProperties = &modelMilvusCollectionProperties
	}
	return pModelMilvusCollectionProperties
}
