// Copyright Siratee K. 2026
// SPDX-License-Identifier: MIT

package collection

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/milvus-io/milvus/client/v2/milvusclient"
	"github.com/milvus-io/milvus/pkg/v2/util/merr"
	"github.com/sirateek/terraform-provider-milvus/internal/resources/collection/converter"
	"github.com/sirateek/terraform-provider-milvus/internal/resources/collection/model"
	"github.com/sirateek/terraform-provider-milvus/internal/resources/collection/plan"
)

var _ resource.Resource = &MilvusCollectionResource{}
var _ resource.ResourceWithConfigure = &MilvusCollectionResource{}
var _ resource.ResourceWithImportState = &MilvusCollectionResource{}

// MilvusCollectionResource is the resource implementation.
type MilvusCollectionResource struct {
	client *milvusclient.Client
}

// NewMilvusCollectionResource is a helper function to simplify the provider implementation.
func NewMilvusCollectionResource() resource.Resource {
	return &MilvusCollectionResource{}
}

// Metadata returns the resource type name.
func (r *MilvusCollectionResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_collection"
}

// Schema defines the schema for the resource.
func (r *MilvusCollectionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Milvus Collection Configs",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				MarkdownDescription: "The unique identifier of the collection generated by Milvus. Computed.",
				Computed:            true,
			},
			"delete_protection": schema.BoolAttribute{
				MarkdownDescription: "This flag prevent accidentally remove the collection by this Provider, Some operation of Milvus require recreation of Collection. Optional, Default to True",
				Computed:            true,
				Optional:            true,
				Default:             booldefault.StaticBool(true),
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the collection. Required and immutable.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description of the collection. Optional and immutable.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"auto_id": schema.BoolAttribute{
				MarkdownDescription: "Whether to automatically generate IDs for primary key field. Optional and immutable.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
				},
			},
			"enable_dynamic_field": schema.BoolAttribute{
				MarkdownDescription: "Whether to enable dynamic field. Optional and immutable.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
				},
			},
			"shard_num": schema.Int64Attribute{
				MarkdownDescription: "Number of shards for the collection. Optional and immutable after creation.",
				Optional:            true,
				Computed:            true,
				Default:             int64default.StaticInt64(1),
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"consistency_level": schema.StringAttribute{
				MarkdownDescription: "Consistency level of the collection. Valid values: Strong, Bounded, Session, Eventually. Optional and mutable.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("Strong"),
			},
			"properties": schema.SingleNestedAttribute{
				MarkdownDescription: "Additional properties for the collection. Optional and mutable.",
				Attributes: map[string]schema.Attribute{
					"collection_ttl_seconds": schema.Int64Attribute{
						MarkdownDescription: "If the data of a collection needs to be deleted after a specific period, consider setting its Time-To-Live (TTL) in seconds. Once the TTL times out, Milvus deletes all entities from the collection.\n\nThe deletion is asynchronous, indicating that searches and queries are still possible before the deletion is complete.",
						Optional:            true,
					},
					"mmap_enabled": schema.BoolAttribute{
						MarkdownDescription: "\t\nMemory mapping (Mmap) enables direct memory access to large files on disk, allowing Milvus to store indexes and data in both memory and hard drives. This approach helps optimize data placement policy based on access frequency, expanding storage capacity for collections without impacting search performance.",
						Optional:            true,
					},
					"partition_key_isolation": schema.BoolAttribute{
						MarkdownDescription: "With Partition Key Isolation enabled, Milvus groups entities based on the Partition Key value and creates a separate index for each of these groups. Upon receiving a search request, Milvus locates the index based on the Partition Key value specified in the filtering condition and restricts the search scope within the entities included in the index, thus avoiding scanning irrelevant entities during the search and greatly enhancing the search performance.",
						Optional:            true,
					},
					"dynamic_field_enabled": schema.BoolAttribute{
						Optional: true,
					},
					"allow_insert_auto_id": schema.BoolAttribute{
						Optional: true,
					},
					"allow_update_auto_id": schema.BoolAttribute{
						Optional: true,
					},
					"timezone": schema.StringAttribute{
						Optional: true,
					},
				},
				Optional: true,
			},
			"fields": schema.ListNestedAttribute{
				MarkdownDescription: "Schema fields for the collection. Required and immutable.",
				Required:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: "Field name. Required.",
							Required:            true,
						},
						"data_type": schema.StringAttribute{
							MarkdownDescription: "Field data type (e.g., Int64, FloatVector, VarChar). Required.",
							Required:            true,
						},
						"is_primary_key": schema.BoolAttribute{
							MarkdownDescription: "Whether this field is the primary key. Optional and computed.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"is_auto_id": schema.BoolAttribute{
							MarkdownDescription: "Whether this field auto-generates IDs. Optional and computed.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"is_partition_key": schema.BoolAttribute{
							MarkdownDescription: "Whether this field is a partition key. Optional and computed.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"is_clustering_key": schema.BoolAttribute{
							MarkdownDescription: "Whether this field is a clustering key. Optional and computed.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"nullable": schema.BoolAttribute{
							MarkdownDescription: "Whether this field is nullable. Optional and computed.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"dim": schema.Int64Attribute{
							MarkdownDescription: "Dimension for vector fields. Optional.",
							Optional:            true,
						},
						"max_length": schema.Int64Attribute{
							MarkdownDescription: "Maximum length for varchar fields. Optional.",
							Optional:            true,
						},
						"max_capacity": schema.Int64Attribute{
							MarkdownDescription: "Maximum capacity for array fields. Optional.",
							Optional:            true,
						},
						"element_type": schema.StringAttribute{
							MarkdownDescription: "Element type for array fields. Optional.",
							Optional:            true,
						},
						"description": schema.StringAttribute{
							MarkdownDescription: "Description of the field. Optional and computed.",
							Optional:            true,
							Computed:            true,
							Default:             stringdefault.StaticString(""),
						},
					},
				},
				PlanModifiers: []planmodifier.List{
					plan.FieldsListPlanModifier{},
				},
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *MilvusCollectionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*milvusclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *milvusclient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

// Create creates the resource and sets the initial Terraform state.
func (r *MilvusCollectionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var resourceModel model.MilvusCollectionResourceModel

	// Read Terraform resourceModel data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &resourceModel)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Extract fields from resourceModel
	var fields []model.FieldModel
	resp.Diagnostics.Append(resourceModel.Fields.ElementsAs(ctx, &fields, false)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Build entity schema
	collSchema, ok := toEntitySchema(ctx, resourceModel, fields)
	if !ok {
		resp.Diagnostics.AddError("Fail to build entity schema", "Please check the fields in the plan.")
		return
	}

	// Build create collection option
	opt := milvusclient.NewCreateCollectionOption(resourceModel.Name.ValueString(), collSchema)

	// Set optional fields
	if !resourceModel.ShardNum.IsNull() {
		opt.WithShardNum(int32(resourceModel.ShardNum.ValueInt64()))
	}

	if !resourceModel.ConsistencyLevel.IsNull() {
		consistencyLevel := consistencyLevelFromString(resourceModel.ConsistencyLevel.ValueString())
		opt.WithConsistencyLevel(consistencyLevel)
	}

	// Handle properties
	if resourceModel.Properties != nil {
		// Convert to Parsed
		parsedMilvusCollectionProperties := converter.
			ConverterInstance.
			MilvusCollectionPropertiesToParsed(resourceModel.Properties)
		marshaledProperties, err := json.Marshal(parsedMilvusCollectionProperties)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error parsing properties",
				fmt.Sprintf("Could not parse properties: %s", err.Error()),
			)
			return
		}

		var parsedData map[string]any
		err = json.Unmarshal(marshaledProperties, &parsedData)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error parsing properties",
				fmt.Sprintf("Could not parse properties: %s", err.Error()),
			)
			return
		}

		for key, value := range parsedData {
			opt.WithProperty(key, value)
		}
	}

	// Create the collection
	err := r.client.CreateCollection(ctx, opt)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating collection",
			fmt.Sprintf("Could not create collection %s: %s", resourceModel.Name.ValueString(), err.Error()),
		)
		return
	}

	// Read back the created collection to populate computed values
	r.readCollection(ctx, &resourceModel, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, &resourceModel)...)
}

// Read refreshes the Terraform state with the latest data.
func (r *MilvusCollectionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state model.MilvusCollectionResourceModel

	// Read Terraform state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Check if collection exists
	exists, err := r.client.HasCollection(ctx, milvusclient.NewHasCollectionOption(state.Name.ValueString()))
	if err != nil {
		resp.Diagnostics.AddError(
			"Error checking collection",
			fmt.Sprintf("Could not check if collection %s exists: %s", state.Name.ValueString(), err.Error()),
		)
		return
	}

	if !exists {
		resp.State.RemoveResource(ctx)
		return
	}

	r.readCollection(ctx, &state, resp.Diagnostics)

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *MilvusCollectionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var planData, stateData model.MilvusCollectionResourceModel

	// Read Terraform planData and stateData data
	resp.Diagnostics.Append(req.Plan.Get(ctx, &planData)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &stateData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Add new scalar fields if any were added to the planData
	resp.Diagnostics.Append(r.addNewScalarFields(ctx, planData, stateData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Update properties if changed
	changedProps := make(map[string]any)
	if planData.Properties != nil || stateData.Properties != nil {
		diffProperties := compareTerraformCollectionPropertyPlanAndState(planData.Properties, stateData.Properties)
		milvusCollectionPropertyBridge := converter.ConverterInstance.MilvusCollectionPropertiesToParsed(diffProperties)
		marshaledProperties, err := json.Marshal(milvusCollectionPropertyBridge)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error parsing properties",
				fmt.Sprintf("Could not parse properties: %s", err.Error()),
			)
			return
		}

		unmarshalErr := json.Unmarshal(marshaledProperties, &changedProps)
		if unmarshalErr != nil {
			resp.Diagnostics.AddError(
				"Error parsing properties",
				fmt.Sprintf("Could not parse properties: %s", unmarshalErr.Error()),
			)
			return
		}
	}

	if len(changedProps) > 0 {
		opt := milvusclient.NewAlterCollectionPropertiesOption(planData.Name.ValueString())
		for key, val := range changedProps {
			opt.WithProperty(key, val)
		}

		err := r.client.AlterCollectionProperties(ctx, opt)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error updating collection properties",
				fmt.Sprintf("Could not update properties for collection %s: %s", planData.Name.ValueString(), err.Error()),
			)
			return
		}
	}

	// Read back the updated collection
	r.readCollection(ctx, &planData, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set stateData
	resp.Diagnostics.Append(resp.State.Set(ctx, &planData)...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *MilvusCollectionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state model.MilvusCollectionResourceModel

	// Read Terraform state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if state.DeleteProtection.ValueBool() {
		resp.Diagnostics.AddError(
			fmt.Sprintf("Collection %s is protected from deletion",
				state.Name.ValueString()), "Cannot delete the resource that has `delete_protection` on. Please confirm your action by first updating the `delete_protection` to false first.",
		)
		return
	}

	collectionName := state.Name.ValueString()

	// Prevent deletion when indexes still exist on the collection.
	// The caller must remove all milvus_index resources linked to this collection
	// before the collection itself can be destroyed, ensuring no index Terraform
	// resource is left orphaned in state.
	indexNames, err := r.client.ListIndexes(ctx, milvusclient.NewListIndexOption(collectionName))
	if err != nil && !errors.Is(err, merr.ErrIndexNotFound) {
		resp.Diagnostics.AddError(
			"Error listing indexes for collection",
			fmt.Sprintf("Could not list indexes on collection %s: %s", collectionName, err.Error()),
		)
		return
	}
	if len(indexNames) > 0 {
		resp.Diagnostics.AddError(
			fmt.Sprintf("Collection %s still has indexes", collectionName),
			fmt.Sprintf(
				"Cannot delete collection %s while the following indexes exist: %v. "+
					"Remove all milvus_index resources linked to this collection first.",
				collectionName, indexNames,
			),
		)
		return
	}

	// Drop the collection
	if err := r.client.DropCollection(ctx, milvusclient.NewDropCollectionOption(collectionName)); err != nil {
		resp.Diagnostics.AddError(
			"Error deleting collection",
			fmt.Sprintf("Could not delete collection %s: %s", collectionName, err.Error()),
		)
		return
	}
}

// ImportState imports the resource by name.
func (r *MilvusCollectionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
